trigger:
  tags:
    include:
      - 'v*'     # publica quando tag vX.Y.Z é criada
  branches:
    exclude:
      - '*'      # evita publicar em every push

pool:
  vmImage: 'ubuntu-latest'

steps:
  - task: NodeTool@0
    inputs:
      checkLatest: true
      versionSpec: '20.x'

  # Autentica no feed usando o .npmrc do repo
  - task: npmAuthenticate@0
    displayName: 'Authenticate to Azure Artifacts feed'
    inputs:
      workingFile: .npmrc

  - script: npm ci
    displayName: Install

  - script: npm run build
    displayName: Build

  # opcional: validação rápida
  - script: npm run typecheck && npm run lint
    displayName: Checks
    continueOnError: true

  - script: npm publish
    displayName: Publish
